; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[platformio]
src_dir = main
default_envs = 
	dev

[env]
build_flags = 
	-D VERSION=3.1.4-beta7
platform = platformio/espressif32 @ ~6.12.0
framework = arduino, espidf
lib_ldf_mode = chain+
monitor_speed = 115200
lib_deps = 
	https://github.com/bblanchon/ArduinoStreamUtils.git#v1.9.2
	https://github.com/bblanchon/ArduinoJson.git#v7.4.3
	https://github.com/mattbaker-digital/Arduino-Log#21ccaa8a61352f78770ad6335225457cd2c14787
	https://github.com/ESP32Async/AsyncTCP.git#v3.4.10
	https://github.com/ESP32Async/ESPAsyncWebServer.git#v3.10.0
	https://github.com/mathieucarbou/MycilaWebSerial#v8.2.1
	https://github.com/jclds139/FS_FilePrint.git#a8b3bae397ce918c49be112c034a0fcbbc5c24fd
	https://github.com/hmueller01/pubsubclient3.git#v3.3.0
	https://github.com/arcao/Syslog#e9c2eea7a91fdda3a55f9df2ebc122f3152da02d
	https://github.com/arjenhiemstra/ArduinoNvs.git
	https://github.com/joltwallet/esp_littlefs.git#v1.16.4
lib_ignore = 
	LittleFS

[project_base]
board_build.filesystem = littlefs
board_build.partitions = ithowifi_parttable_coredump.csv
monitor_filters = esp32_exception_decoder
extra_scripts = 
	build_script.py
build_unflags = -std=gnu99 -std=gnu++11
build_flags = 
	-std=gnu++2a
	-std=gnu17
	-Os
	-DMG_ARCH=MG_ARCH_ESP32
	-DMAX_NUM_OF_REMOTES=12
	-DCONFIG_ASYNC_TCP_STACK_SIZE=8192
	-DCONFIG_ASYNC_TCP_RUNNING_CORE=1
	-DWS_MAX_QUEUED_MESSAGES=8
	-fno-strict-aliasing -fexceptions -fstack-protector -ffunction-sections -fdata-sections -fstrict-volatile-bitfields
	-mlongcalls -nostdlib
	-g0
	-Wall -Wextra
	-Wunused-but-set-variable -Wdeprecated-declarations -Wno-error=format

[env:dev]
extends = project_base
monitor_filters = esp32_exception_decoder
build_flags = 
	${project_base.build_flags}
	${env.build_flags}
	-DENABLE_SERIAL
board = esp32dev

[env:beta]
extends = project_base
build_flags = 
	${project_base.build_flags}
	${env.build_flags}
	-DBETA
board = esp32dev

[env:release]
extends = project_base
build_flags = 
	${project_base.build_flags}
	${env.build_flags}
	-DSTABLE
board = esp32dev

[env:debug]
extends = project_base
build_flags = 
	${project_base.build_flags}
	${env.build_flags}
build_type = debug
board = esp-wrover-kit
framework = arduino
upload_protocol = ftdi
debug_tool = ftdi
debug_init_break = tbreak setup

[env:native_test]
platform = native
framework = 
test_framework = unity
build_flags = 
	-D UNIT_TEST
	-std=gnu++17
	-I test/test_native/mocks
test_filter = test_native_*
lib_deps = 
	bblanchon/ArduinoJson@^7.0.0
