#pragma once

#include "error_info_labels.h"

const uint16_t itho_HRU350setting1[]{0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84, 85, 86, 87, 88, 89, 90, 91, 92, 999};
const uint16_t itho_HRU350setting3_4[]{0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 70, 71, 72, 73, 74, 76, 77, 78, 79, 80, 93, 81, 94, 95, 96, 97, 98, 99, 100, 101, 102, 103, 104, 105, 106, 107, 108, 109, 110, 111, 112, 113, 114, 115, 116, 89, 90, 91, 92, 999};

const char *ithoHRU350SettingsLabels[] = {
    "Percentage set 2 (%)",
    "Temp frost protection (°C)",
    "Frost temp offset (°C)",
    "Min frost speed (%)",
    "Max frost speed (%)",
    "Frost supply fan off time (Sec)",
    "Frost supply fan on time (Sec)",
    "Frost speed change (%)",
    "Frost speed change (%)",
    "Max ratio exhaust - supply during frost protection (%)",
    "Summer temp (°C)",
    "Summer temp GHE (°C)",
    "Summer day time (K*hr)",
    "Wanted temp bypass regulation (°C)",
    "Offset bypass regulation (K)",
    "Max bypass open time (hrs)",
    "Max rpm fast var. Pwm (RPM)",
    "Max rpm slow var. Pwm (RPM)",
    "Max rpm  fast fixed pwm (RPM)",
    "Speed offset (RPM)",
    "High frequency var pwm (kHz)",
    "Low frequency var pwm (kHz)",
    "High frequency fixed pwm (kHz)",
    "Low frequentie fixed pwm (kHz)",
    "Start speed vkk exhaust fan (%)",
    "Vkk valve close time (Sec)",
    "Rpm exhaust fan with min position potmeter low (RPM)",
    "Rpm exhaust fan with max position potmeter low (RPM)",
    "Rpm exhaust fan with vkk with min position potmeter low (RPM)",
    "Rpm exhaust fan with vkk with max position potmeter low (RPM)",
    "Rpm exhaust fan with min position potmeter high (RPM)",
    "Rpm exhaust fan with max position potmeter high (RPM)",
    "Min rpm supply fan (RPM)",
    "Max rpm supply fan (RPM)",
    "Min value balance setting (%)",
    "Max value balance setting (%)",
    "Min zeta supply value",
    "Max zeta supply value",
    "Stop both motors with motor fault",
    "Correction rpm with min rpm during bypass (%)",
    "Correction rpm with max.rpm during bypass (%)",
    "HRU version",
    "OEM value",
    "Supply fan of during vkk test",
    "Manual control",
    "Manual speed supply fan (RPM)",
    "Manual speed exhaust fan (RPM)",
    "Manual valve position",
    "Air quality",
    "Filter live time (Month)",
    "Filter counter (Hours)",
    "Output Constant Ca2",
    "Output Constant Ca1",
    "Output Constant Ca0",
    "Output Constant Cb2",
    "Output Constant Cb1",
    "Output Constant Ca0",
    "Output Constant Cc2",
    "Output Constant Cc1",
    "Output Constant Cc0",
    "Supply Constant Ca2",
    "Supply Constant Ca1",
    "Supply Constant Ca0",
    "Supply Constant Cb2",
    "Supply Constant Cb1",
    "Supply Constant Cb0",
    "Supply Constant Cc2",
    "Supply Constant Cc1",
    "Supply Constant Cc0",
    "PIR level 1 (%)",
    "PIR level 2 (%)",
    "PIR level 1 wait time (sec)",
    "PIR level 2 wait time (sec)",
    "PIR run-on level 1 (sec)",
    "PIR run-on level 2 (sec)",
    "Min ventilation level (%)",
    "Max time High speed (Min)",
    "Max time other speeds (Min)",
    "Fallback previous speeds (-)",
    "PoorCo2Quality (ppm)",
    "GoodCo2Quality (ppm)",
    "Inhabitants (inhab)",
    "Night min vent speed 1 person (%)",
    "Night min vent speed 2 persons (%)",
    "Night min vent speed 3 or more persons (%)",
    "Debug only (sec)",
    "Debug only (sec)",
    "Debug only (min)",
    "Debug only (K_min)",
    "BypassTimer (min)",
    "MaximumOpenCounter (min)",
    "FilterUsagePerMin (-)",
    "Balance (%)",
    "Number of floors (floor)",
    "Min ventilation level multi-floor (%)",
    "Min ventilation level one-floor (%)",
    "Night min vent optima 1 multi-floor 1 person (%)",
    "Night min vent optima 1 multi-floor 2 persons (%)",
    "Night min vent optima 1 multi-floor 3+ persons (%)",
    "Night min vent optima 1 one-floor 1 person (%)",
    "Night min vent optima 1 one-floor 2 persons (%)",
    "Night min vent optima 1 one-floor 3+ persons (%)",
    "Night min vent optima 2 multi-floor 1 person (%)",
    "Night min vent optima 2 multi-floor 2 persons (%)",
    "Night min vent optima 2 multi-floor 3+ persons (%)",
    "Night min vent optima 2 one-floor 1 person (%)",
    "Night min vent optima 2 one-floor 2 persons (%)",
    "Night min vent optima 2 one-floor 3+ persons (%)",
    "Summer night boost enable (-)",
    "Summer night degree (-)",
    "Summer night setpoint (°C)",
    "Summer night boost ventilation level (%)",
    "Summer night max area degree hours (-)",
    "FrostTimer (sec)",
    "StartupCounter (sec)",
    "BoilerTestTimer (min)",
    "SummerCounter (K_min)"};

const uint8_t itho_HRU350status1_4[]{0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 255};

const struct ithoLabels ithoHRU350StatusLabels[]{
    {"Requested fanspeed (%)", "requested-fanspeed_perc"},
    {"Balance (%)", "balance_perc"},
    {"Supply fan (RPM)", "supply-fan_rpm"},
    {"Supply fan actual (RPM)", "supply-fan-actual_rpm"},
    {"Exhaust fan (RPM)", "exhaust-fan_rpm"},
    {"Exhaust fan actual (RPM)", "exhaust-fan-actual_rpm"},
    {"Supply temp (°C)", "supply-temp_c"},
    {"Exhaust temp (°C)", "exhaust-temp_c"},
    {"Status", "status"},
    {"Room temp (°C)", "room-temp_c"},
    {"Outdoor temp (°C)", "outdoor-temp_c"},
    {"Valve position", "valve-position"},
    {"Bypass position", "bypass-position"},
    {"Summercounter", "summercounter"},
    {"Summerday (K_min)", "summerday_kmin"},
    {"Frost timer", "frost-timer"},
    {"Boiler timer", "boiler-timer"},
    {"Frost block", "frost-block"},
    {"Current position", "current-position"},
    {"VKKswitch", "vkkswitch"},
    {"GHEswitch", "gheswitch"},
    {"Airfilter counter", "airfilter-counter"},
    {"Global fault code", "global-fault-code"},
    {"Actual Mode", "actual-mode"},
    {"Pir fan speed level", "pir-fan-speed-level"},
    {"Highest received CO2 value (Ppm)", "highest-received-co2-value_ppm"},
    {"Highest received RH value (%RH)", "highest-received-rh-value_rh"},
    {"Air Quality (%)", "air-quality_perc"},
    {"Remaining override timer (Sec)", "remaining-override-timer_sec"},
    {"Fallback speed timer (Sec)", "fallback-speed-timer_sec"}};

const uint16_t *ithoHRU350SettingsMap[] = {nullptr, itho_HRU350setting1, nullptr, itho_HRU350setting3_4, itho_HRU350setting3_4};
const uint8_t *ithoHRU350StatusMap[] = {nullptr, itho_HRU350status1_4, nullptr, itho_HRU350status1_4, itho_HRU350status1_4};
