M48
; DRILL file {KiCad (7.0.0-0)} date Tuesday, 06 June 2023 at 23:20:26
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2023-06-06T23:20:26+02:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,(7.0.0-0)
; #@! TF.FileFunction,NonPlated,1,4,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C2.500
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C3.250
%
G90
G05
T1
X55.482Y-109.381
X55.482Y-153.704
X113.013Y-109.508
X113.013Y-153.704
T2
X56.832Y-132.256
X56.832Y-144.957
T0
M30
