M48
; DRILL file {KiCad (6.0.1-0)} date 2022 February 11, Friday 21:02:16
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2022-02-11T21:02:16+01:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,(6.0.1-0)
; #@! TF.FileFunction,NonPlated,1,4,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.991
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C3.200
%
G90
G05
T1
X89.496Y-107.901
X94.576Y-106.885
X94.576Y-108.917
T2
X94.488Y-113.538
X121.63Y-108.12
T0
M30
