M48
; DRILL file {KiCad (7.0.0-0)} date Wednesday, 07 June 2023 at 10:33:51
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2023-06-07T10:33:51+02:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,(7.0.0-0)
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C2.500
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C3.000
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T3C3.250
%
G90
G05
T1
X131.0Y-74.0
X131.0Y-101.5
X158.369Y-74.0
X158.369Y-101.5
T2
X140.097Y-100.782
X148.597Y-100.882
T3
X138.004Y-74.473
X150.704Y-74.473
T0
M30
